[2025-10-20T16:30:56.627+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab1_HeartDisease.load_data manual__2025-10-20T16:30:55.249516+00:00 [queued]>
[2025-10-20T16:30:56.630+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab1_HeartDisease.load_data manual__2025-10-20T16:30:55.249516+00:00 [queued]>
[2025-10-20T16:30:56.631+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T16:30:56.631+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-10-20T16:30:56.631+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T16:30:56.636+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_data> on 2025-10-20 16:30:55.249516+00:00
[2025-10-20T16:30:56.639+0000] {standard_task_runner.py:55} INFO - Started process 113 to run task
[2025-10-20T16:30:56.641+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1_HeartDisease', 'load_data', 'manual__2025-10-20T16:30:55.249516+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpigl5ugys']
[2025-10-20T16:30:56.641+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask load_data
[2025-10-20T16:30:56.664+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow_Lab1_HeartDisease.load_data manual__2025-10-20T16:30:55.249516+00:00 [running]> on host c8bdb2420cbf
[2025-10-20T16:30:56.693+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gnanasudharsan
AIRFLOW_CTX_DAG_ID=Airflow_Lab1_HeartDisease
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2025-10-20T16:30:55.249516+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-20T16:30:55.249516+00:00
[2025-10-20T16:30:56.702+0000] {logging_mixin.py:137} INFO - âœ… Data Loaded Successfully: (300, 14)
[2025-10-20T16:30:56.702+0000] {python.py:177} INFO - Done. Returned value was:             age            sex               cp  ...  ca               thal target
id  age     sex        dataset               cp  ...  ca               thal    num
1   63     Male      Cleveland   typical angina  ...   0       fixed defect      0
2   67     Male      Cleveland     asymptomatic  ...   3             normal      2
3   67     Male      Cleveland     asymptomatic  ...   2  reversable defect      1
4   37     Male      Cleveland      non-anginal  ...   0             normal      0
...         ...            ...              ...  ...  ..                ...    ...
300 68     Male      Cleveland     asymptomatic  ...   2  reversable defect      2
301 57     Male      Cleveland     asymptomatic  ...   1  reversable defect      3
302 57   Female      Cleveland  atypical angina  ...   1             normal      1
509 47     Male        Hungary     asymptomatic  ...   0  reversable defect      1
749 56     Male  VA Long Beach     asymptomatic  ...   0  reversable defect      1

[300 rows x 14 columns]
[2025-10-20T16:30:56.714+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-10-20T16:30:56.715+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2025-10-20T16:30:56.718+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Airflow_Lab1_HeartDisease, task_id=load_data, execution_date=20251020T163055, start_date=20251020T163056, end_date=20251020T163056
[2025-10-20T16:30:56.722+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task load_data (Object of type DataFrame is not JSON serializable; 113)
[2025-10-20T16:30:56.739+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-20T16:30:56.748+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
